### PR TITLE
feat: add rating resource introduction

### PR DESCRIPTION
**Pull request by 0xff-dev**
feat: add rating resource introduction

### CODE REVIEW

**Review by Abirdcfly — APPROVED** [review]

**Comment by 0xff-dev** [comment]
> /hold For further updates

Done. We can continue to review.

**Comment by bjwswang** [comment]
@0xff-dev @Abirdcfly We can add a [WIP] in the title to indicate this is not ready to be merged yet.

**Review by bjwswang — APPROVED** [review]
Pls add another document in UserGuide to teach user on how to enable rating in kubebb

**Pull request merged**
